version: '2'
services:
    euphoriajavav1-app:
        image: euphoriajavav1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://euphoriajavav1-mysql:3306/euphoriajavav1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8081:8081
    euphoriajavav1-mysql:
        extends:
            file: mysql.yml
            service: euphoriajavav1-mysql
